### PR TITLE
Add an external url support for reverse proxy configurations

### PR DESCRIPTION
**Pull request by hasso**
The code is adapted from Alertmanager code.

### CODE REVIEW

**Comment by hasso** [comment]
I actually think that all components might benefit from this feature, so maybe it makes sense to standardise it somehow.

**Comment by brian-brazil** [comment]
External urls are for UIs intended to be used by a browser. The blackbox exporter is not such a system.

**Comment by hasso** [comment]
So, how I should use blackbox exporter behind https://hostname/blackbox_exporter reverse proxy?

**Comment by brian-brazil** [comment]
I'd presume it'd be https://hostname/blackbox_exporter/probe

**Comment by hasso** [comment]
That's the part I understand obviously ;). But it might need some serious rewrite stuff depending on proxy in use and leaves front page links broken. Yes, I understand that these are for demo mostly, but still.

**Comment by brian-brazil** [comment]
This is standard reverse proxy usage, there shouldn't be anything too complicated.

The front page links are more for those using it for the first time, them breaking in a more complex use isn't the end of the world.

**Comment by hasso** [comment]
OK. Let it be then.

**Pull request closed without merging**
