### PR TITLE
Add use_proxy_dns to bypass local DNS resolution

### PR DESCRIPTION
**Pull request by Scapal**
Addressing issue #553 and possibly #264 .

### CODE REVIEW

**Comment by brian-brazil** [comment]
As indicated this breaks other features, so doesn't make sense. As I've previously stated I'd consider a feature to better test HTTP proxies, but DNS resolution of whatever is passed in with the URL needs to stay inside the blackbox exporter.

**Comment by Scapal** [comment]
I really don't get it why you states it breaks other features.
The purpose of black box monitoring is end to end testing: "does it works from here".
Even now when using the existing proxy option you actually don't control the IP protocol used to connect to the proxy, only the target host.
If you use the option, you know it bypasses the local DNS resolution and IP protocol selection, what is wrong with that?

Please reconsider accepting this PR.

**Comment by brian-brazil** [comment]
The purpose of the blackbox exporter is to test many many replicas of a service, including knowing what it was that you actually tested.

If a proxy does resolution we don't know what was tested, and as mentioned before that http proxies are supported at all is because it happens to come from the http library we use - it was never an intended feature of the blackbox exporter. If you need to test things at the far end of a proxy, you can have Prometheus use the proxy_url and put the blackbox exporter on the other side of the proxy.

**Comment by Scapal** [comment]
We are not authorised to install an exporter on the far end of the proxy and the purpose is to test wether the service is working from here.
For example, one of my customer HQ moved servers to another network segment. It was transparent for users on the headquarter network but stopped working for branch offices forced to use the proxy.
Blackbox_exporter should imho stay a Swiss army knife. Monitoring many many replicas of a services being just one possible usage.
Even in your use case, using a Docker service IP address would also go through load-balancers...

**Comment by brian-brazil** [comment]
We can't cover every possible deployment model to work in the easiest way possible I'm afraid, and we end up presuming that there is only one DNS view. Monitoring many many replicas of a service is explicitly the design goal, in this case the idea would be to test that each of multiple proxy servers work for getting to some HTTP fixed endpoint - which isn't supported as noone has proposed a PR/design yet.

I believe what I proposed would have caught that particular issue, as Prometheus wouldn't have been able to get to the blackbox exporter.

> We are not authorised to install an exporter on the far end of the proxy and the purpose is to test wether the service is working from here.

Unfortunately we can't help with problems arising due to internal policies/politics, as otherwise that becomes a general argument for everything.

**Comment by Scapal** [comment]
Could we have additional opinions about this PR or are you the sole contributor to have a voice for this repository ?

**Comment by brian-brazil** [comment]
I'm the sole maintainer of this repo, per our governance you can bring it up on the developers list.

**Comment by mblaschke** [comment]
Hm.. that would maybe also solve our issue within the corporate network.

Something similar I already tried to address with https://github.com/prometheus/blackbox_exporter/issues/543 and https://github.com/prometheus/blackbox_exporter/pull/545

**Comment by pbeaumontQc** [comment]
We also need this and have been monitoring answer since issue #303 ... We have a list of third party providers that we need to monitor, as a breakdown from one of them directly breaks our ability to function. Our instances are hosted on AWS EC2 and all go through a proxy to the 3rd party providers... Any update on this much desired feature?

**Comment by brian-brazil** [comment]
As I've already indicated this feature as-stated will not be accepted. I'd suggest looking at moving where the exporter runs, or fixing your proxy server to work with IP addresses.

**Comment by lyz-code** [comment]
Although it's stated that it won't be implemented, I'd also need this feature.

The ugly workaround I'm implementing is creating "fake" DNS records in my internal DNS server so the probe sees they exist and then the probe works as expected

**Comment by riuvshyn** [comment]
This is frustrating... I also need this feature.

**Comment by riuvshyn** [comment]
> As indicated this breaks other features

@brian-brazil  can you please elaborate on what exact features will be impacted by this change?

Most proxy setups do ACLs based on DNS names because IPs are not constants. 
The proposed change is optional and will not affect users who are not using HTTP proxy but those who using proxy can use Blackbox exporter without this at all...

**Comment by brian-brazil** [comment]
As indicated above, it breaks the ability to see what you talked to.

I'll be closing this now, as there's no plans to accept any feature like this. As previously stated I am willing to consider features to allow probing of http proxies.

**Comment by dbluxo** [comment]
We would also be happy about this feature :disappointed:

**Comment by riuvshyn** [comment]
@dbluxo that is why there are 552 forks ;)

**Comment by dbluxo** [comment]
Like this PR, [PR-338](https://github.com/prometheus/blackbox_exporter/pull/338) was also rejected. Also with the hint to discuss it on the prometheus developers list. Has anyone tried it yet?

**Comment by riuvshyn** [comment]
@dbluxo changes in this PR works perfectly fine.

**Comment by ChristianCiach** [comment]
Can you guys recommend a fork that fixes this? I don't have much trust in a project that is maintained by a single person anyway, but given his comments on this and other issues I've lost any remaining trust that I may have had before.

**Pull request closed without merging**
