### PR TITLE
Extend information about last cert of chain

### PR DESCRIPTION
**Pull request by vadimgs**
Add to registry information about expiration time fro last certs of chain
probe_ssl_last_cert_expiry

### CODE REVIEW

**Comment by brian-brazil** [comment]
How is this useful?

**Comment by vadimgs** [comment]
@brian-brazil This is necessary to obtain information on the latest certificate. Since it is necessary in the chain of certificates

**Comment by brian-brazil** [comment]
How does this differ from what we already have?

**Comment by dkutetsky** [comment]
> How does this differ from what we already have?

This is a fix for the issue https://github.com/prometheus/blackbox_exporter/issues/340.
Currently, blackbox returns the earliest expiration in a chain, but in the real world, we need an another behavior - we should get expiration date of the last certificate in the chain (should be the same as in OpenSSL/Chrome).
So, @vadimgs extends the result with another field that is will be useful for getting the same results we had in browsers.
I described exactly implemented behavior here -https://github.com/prometheus/blackbox_exporter/issues/442

**Comment by brian-brazil** [comment]
This doesn't sound like a fix for #340, as you'd (presumably) get an arbitrary cert rather than the earliest chain.

**Comment by dkutetsky** [comment]
I will get exactly site certificate expiration date - we tested it with our case and it works fine :)

**Comment by algestam** [comment]
+1

The last cert in the chain is usually the site/domain specific certificate. Information on the expiry date for this certificate is useful since it is the often the only one in the chain that needs to be re-ordered from the certificate issuer before the validation end date.

**Comment by brian-brazil** [comment]
However if an intermediate cert is going to expire first, you want to know about that.

**Comment by algestam** [comment]
Definitely! Both properties are useful but for different purposes. The earliest expire property gives the time until the earliest expiry in the chain and the new property (last in chain) is useful for planning when a new certificate is to be ordered.

**Comment by brian-brazil** [comment]
In both cases you need to take action, so this new metric wouldn't add anything.

**Comment by algestam** [comment]
I don't agree there :) I have a certificate that is issued to expire in ~2 years. The cert chain however contains an AddTrust External CA Root certificate that expires on May 30th 2020. There is however no action needed from my end as I understand it based on this: https://www.xolphin.com/support/Rootcertificates/Phasing_out_Addtrust_External_CA_Root_certificate

The earliest expiry property correctly returns the time until the earliest expiry which is the AddTrust certificate but I'm also interested in when my site certificate (last cert in chain) expires so that a new cert is ordered in time.

**Comment by brian-brazil** [comment]
You're assuming that everyone in the chain is being diligent, and checking that it's all okay is a human action.

**Comment by algestam** [comment]
I will still continue to use the earliest expiry property to monitor the overall validity of the cert but the last expiry property complements my needs since that is the only certificate in my chain that I need to manually re-order when the expiry date closes in.

**Comment by brian-brazil** [comment]
This isn't a fix for #340, and I'm not seeing how this helps in general.

**Comment by pir8g33k** [comment]
> > How does this differ from what we already have?
> 
> This is a fix for the issue #340.
> Currently, blackbox returns the earliest expiration in a chain, but in the real world, we need another behavior - we should get expiration date of the last certificate in the chain (should be the same as in OpenSSL/Chrome).
> So, @vadimgs expanded the result with another field (probe_ssl_last_cert_expiry) that is will be useful for getting the same results we had in browsers.
> I described exactly implemented behavior here -#442

are you able to resolved or find a solution for this one sir? @dkutetsky

**Pull request closed without merging**
