### PR TITLE
added http.http_proxy setting

### PR DESCRIPTION
**Pull request by tux21b**
added a setting to set an http proxy that defaults to the proxy from the environment.

### CODE REVIEW

**Comment by brian-brazil** [comment]
This should follow the same proxy_url naming as Prometheus, and have the same validation etc.

We also don't promise anything in terms of reading from the enviroment.

**Comment by tux21b** [comment]
Sounds reasonable. Thanks for your feedback! I'll update the pull request tomorrow.

**Comment by dbaumgarten** [comment]
Is anyone still working on this? This feature would be extremely useful to me right now.
I need to probe the availability of different http proxys and without this PR this seems not to be possible.
@tux21b if you don't have the time for this at the moment, I would happily continue working on this.

**Comment by tux21b** [comment]
@dbaumgarten feel free to continue working on this change - I am afraid I will not have time for this until the weekend.

**Comment by brian-brazil** [comment]
This was added in another PR today.

**Pull request closed without merging**
