### PR TITLE
Add stale workflow to start sync with stale.yaml in prometheus

### PR DESCRIPTION
**Pull request by electron0zero**
create the .github/workflows/stale.yml for automation to register and keep it sync it in sync with https://github.com/prometheus/prometheus/blob/main/.github/workflows/stale.yml

---
~~Add github actions workflow using https://github.com/actions/stale.~~

~~It runs [everyday](https://crontab.guru/#0_0_*_*_*) and marks issues and pull requests stale with no activity in last 90 days, and it will close stale issues and pull requests without activity for 30 days (_120 days before an issue is closed_)~~

~~issues and pull requests that has label `keepalive`, `dependencies`, or `bug` will be excluded by the workflow.~~

~~goal of this workflow is to make it easier for maintainer to maintain the project and close out old issues and PR with automation and save maintainers time :)~~

~~ps: when we merge this PR, this workflow will mark issues and pull requests stale that had no activity in last 90 days.~~

### CODE REVIEW

**Comment by SuperQ** [comment]
I wonder if we should have a Prometheus dev discussion about stale bot. I would prefer to keep this setup consistent between projects.

**Comment by electron0zero** [comment]
> I wonder if we should have a Prometheus dev discussion about stale bot. I would prefer to keep this setup consistent between projects.

yes, I was looking to see how prometheus does it, and found [this PR](https://github.com/prometheus/prometheus/pull/6826#issue-565878511), which links to [Prometheus 2019 Dev Summit 2](https://docs.google.com/document/d/1VVxx9DzpJPDgOZpZ5TtSHBRPuG5Fr3Vr6EFh8XuUpgs/edit#heading=h.17mnxm14bjw5), which says:

> Beorn: General repository health
> - Should be use a bot to mark PRs as stale & close them?
> - CONSENSUS: We should have a bot mark PRs as stale, all repos, 60 days.


but it's using [probot app](https://github.com/probot/stale), which is archived now.

Option 1: align this bot's config to match what we have in `prometheus/prometheus`, but I would prefer to use https://github.com/actions/stale because https://github.com/probot/stale is archived :)

Option 2: I can raise a PR in `prometheus/prometheus` to use https://github.com/actions/stale, and start a proposal in the mailing list to get consesus it. once approved, we can use that in our repo, and other exporters.

I am leaning towards option 2.

**Comment by SuperQ** [comment]
My recommendation
* Open a PR to convert `prometheus/prometheus` from `probot/stale` to `actions/stale`.
* Keep the behavior as specified in the old config.
* Add the `stale.yml` to `scripts/sync_repo_files.sh` so that it's copied everywhere.
* Cleanup the old probot version that's still hanging around in a few places.

There's no need for a new consensus, as we already decided that we should have this everywhere. We just didn't roll it out. :joy_cat:

**Comment by electron0zero** [comment]
opened https://github.com/prometheus/prometheus/pull/14650.

going to close this because once https://github.com/prometheus/prometheus/pull/14650 is merged, config will be synced to our repo.

**Comment by electron0zero** [comment]
reopening this PR because we need to create the `.github/workflows/stale.yml` for automation to register and keep it sync it in sync with https://github.com/prometheus/prometheus/blob/main/.github/workflows/stale.yml

see logs from a [recent repo_sync](https://github.com/prometheus/prometheus/actions/runs/10908291901/job/30273919108) run
image

**Pull request merged**
