### PR TITLE
Add resolved IP address as a label on the protocol field

### PR DESCRIPTION
**Pull request by imduffy15**
Adds the resolved IP as a label to allow for tracking IP changes.

### CODE REVIEW

**Comment by brian-brazil** [comment]
This would be a breaking change, and in addition may pose cardinality issues.

**Comment by imduffy15** [comment]
Can we come to a resolution or should I close and fork?

**Comment by brian-brazil** [comment]
What do you propose? This sort of thing is generally best handled via logging, a given endpoint could easily have thousands of IPs over time.

**Comment by imduffy15** [comment]
Closing in favor of logs.

**Pull request closed without merging**
