### PR TITLE
Update prometheus/common to support --log.format option

### PR DESCRIPTION
**Pull request by shusugmt**
Support for json format logging in `prometheus/common/promlog` has been added since https://github.com/prometheus/common/pull/136
This PR updates `prometheus/common` to the latest version which supports `--log.format` option. 

The update also includes code change to adopt https://github.com/prometheus/common/pull/129
As a result now http prober exposes new metrics described in https://github.com/prometheus/prometheus/pull/3241 via `/metrics` endpoint.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for working on this. The newer version of common also makes all http connections use keepalives, which is undesirable for this particular exporter. That'll need work first.

**Comment by shusugmt** [comment]
I just noticed there are a few similar branches trying to update `prometheus/common`
- https://github.com/prometheus/blackbox_exporter/tree/fish-update-dependencies
- https://github.com/prometheus/blackbox_exporter/tree/bjk/prom_common

And found this PR https://github.com/prometheus/blackbox_exporter/pull/321
Then that leads to https://github.com/prometheus/common/pull/133 which seems blocking this to proceed.

**Comment by shusugmt** [comment]
> The newer version of common also makes all http connections use keepalives, which is undesirable for this particular exporter

Solution seems quite straightforward once https://github.com/prometheus/common/pull/133 got merged. Simply pass `true` as the third parameter to `NewClientFromConfig()` in https://github.com/prometheus/blackbox_exporter/pull/393/files#diff-29df7d46fe6b972c1946a34608c58ab3R219

**Comment by brian-brazil** [comment]
This is obsolete.

**Pull request closed without merging**
