### PR TITLE
Add option to disable TLS certificate check in DoT

### PR DESCRIPTION
**Pull request by edevil**
Similar to TLS probe

### CODE REVIEW

**Comment by brian-brazil** [comment]
Should we have all of the standard tls config stuff here?

**Comment by edevil** [comment]
@brian-brazil I had that question. But since there already is a TLS probe with those options, I suppose the logical thing is to use that one to test for custom TLS stuff, if you need it, and just disable TLS verification in DoT.

In other words, use the DNS and TLS probe in tandem. What do you think?

**Comment by brian-brazil** [comment]
My point is that we already have a standard way of producing a `tls.Config`, so you should use that.

**Comment by edevil** [comment]
I added the TLSConfig block to the DNS probe.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by edevil** [comment]
@brian-brazil No, thank you! Are there any plans to release a new version of blackbox_exporter?

**Comment by brian-brazil** [comment]
Hopefully in the next few days.

**Pull request merged**
