### PR TITLE
Add source_ip_address support to http probes

### PR DESCRIPTION
**Pull request by bobrik**
This is a logical continuation of #262.

It's the same as #765 but without changing `prometheus/common` as @roidelapluie suggested.

Signed-off-by: Ivan Babrou <github@ivan.computer>

### CODE REVIEW

**Comment by bobrik** [comment]
@roidelapluie, this approach doesn't seem to work very well, given that there may be multiple layers of transport.

**Comment by roidelapluie** [comment]
> @roidelapluie, this approach doesn't seem to work very well, given that there may be multiple layers of transport.

Can you be more explicit?

**Comment by bobrik** [comment]
Look at the failed test:

```
panic: interface conversion: http.RoundTripper is *config.basicAuthRoundTripper, not *http.Transport
```

I don't see a good way to update `DialContext` in `http.RoundTripper` that is wrapped by `config.basicAuthRoundTripper`.

**Comment by roidelapluie** [comment]
Hello @bobrik . Now the HTTP client supports passing special dialcontext funcs so we could implement all this in the blackbox exporter: https://github.com/prometheus/common/pull/291

**Pull request closed without merging**
