### PR TITLE
Workaround missing Host header following redirects

### PR DESCRIPTION
**Pull request by timonwong**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add a unittest for this please?

**Comment by timonwong** [comment]
@brian-brazil Done

**Comment by brian-brazil** [comment]
Hmm, is this a bug in Go's http library? This feels like something we shouldn't need to do.

**Comment by timonwong** [comment]
Yeah, I fired a issue on go issue tracker: golang/go#22233

However, Is there any chance to workaround suck issue, because blackbox_exporter currently not working well with virtual hosts & relative path redirects)?

**Comment by timonwong** [comment]
I'm using go1.9.1

**Comment by brian-brazil** [comment]
What I say we do is give it a few days to see what the response is back from the Go team, and if it doesn't look like it's getting fixed in the next major release we'll include it with a pointer to the bug. Sound good?

**Comment by timonwong** [comment]
Certainly no problem at all :) Thanks

**Comment by brian-brazil** [comment]
Doesn't look like this made it into 1.9.3.

**Comment by swade1987** [comment]
can this be merged?

Currently, my Prometheus ingress probe is failing as `prometheus.example.com` gets redirected to `prometheus.example.com/graph` and the probe fails.

**Comment by brian-brazil** [comment]
This is in the Go 1.10 beta.

**Comment by eliecharra** [comment]
@brian-brazil Seems to be fixed by https://github.com/golang/go/commit/47f4e7a9768a613371ccd4a94a6b325fd603727e in 1.10 (just tested) :+1: 

The bug affect only relative redirect headers (e.g "Location: /url" not "Location: example.com/url")

selection_101
selection_099
selection_100
selection_098

IMO we can close this MR as we dont need to test this behaviour here, its related and covered by golang net/http.

**Comment by brian-brazil** [comment]
0.12.0 is out now built with Go 1.10

**Comment by auhlig** [comment]
Just updated to `0.12.0` and this is still valid for me. Blackbox exporter is not following the redirect. 
```
ts=2018-03-01T16:06:00.673302038Z caller=main.go:116 module=http_2xx target=https://<url>/ level=info msg="Beginning probe" probe=http timeout_seconds=54.5
ts=2018-03-01T16:06:00.673565691Z caller=utils.go:42 module=http_2xx target=https://<url>/ level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2018-03-01T16:06:00.68188966Z caller=utils.go:65 module=http_2xx target=https://<url>/ level=info msg="Resolved target address" ip=10.44.11.253
ts=2018-03-01T16:06:00.681983807Z caller=http.go:282 module=http_2xx target=https://<url>/ level=info msg="Making HTTP request" url=https://[10.44.11.253]/ host=<url>
ts=2018-03-01T16:06:00.691325443Z caller=http.go:300 module=http_2xx target=https://<url>/ level=info msg="Received HTTP response" status_code=300
ts=2018-03-01T16:06:00.691378942Z caller=http.go:315 module=http_2xx target=https://<url>/ level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=300
ts=2018-03-01T16:06:00.691432441Z caller=http.go:354 module=http_2xx target=https://<url>/ level=info msg="Response timings for roundtrip" roundtrip=0 start=2018-03-01T16:06:00.682153663Z dnsDone=2018-03-01T16:06:00.682153663Z connectDone=2018-03-01T16:06:00.682579Z gotConn=2018-03-01T16:06:00.688826011Z responseStart=2018-03-01T16:06:00.69126503Z end=2018-03-01T16:06:00.691313919Z
ts=2018-03-01T16:06:00.691580366Z caller=main.go:129 module=http_2xx target=https://<url>/ level=error msg="Probe failed" duration_seconds=0.018145349
```

**Comment by brian-brazil** [comment]
That's a straight-up probe failure.

**Comment by auhlig** [comment]
I’m blind. It’s a `300`, not `301`. Apologies.

**Comment by elftech** [comment]
Why there's no description??

**Pull request closed without merging**
