### PR TITLE
Bumping DNS dependency to 1.1.25

### PR DESCRIPTION
**Pull request by davidcollom**
This resolves issues reported within `miekg/dns` module: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMIEKGDNS-537825

### CODE REVIEW

**Comment by brian-brazil** [comment]
CI is failing.

**Comment by davidcollom** [comment]
Hi @brian-brazil, Thanks for pointing this, out I was aware of the failure. However I'm not 100% familiar with this project and was hoping that the maintainers may be able to point me in the right direction in fixing this?

**Comment by brian-brazil** [comment]
I don't think this is anything to do with our internals, it looks to be a general updating dependencies issue. Try updating everything.

**Comment by davidcollom** [comment]
@brian-brazil Thanks for the pointer, having looked at the dependencies I noticed the following out of date/considerably older releases.

- `prometheus/client_golang`
- `prometheus/common`
- `prometheus/client_model`

Updating those, seems to have resolved the CI builds.

WRT: 
> However I'm not 100% familiar with this project's internals 

The main readme states building the binaries can be done via `make` - https://github.com/prometheus/blackbox_exporter#building-the-software

These where the actions I completed post upgrading the dns library, it may be worth a Contributing section to outline any other actions others should complete prior to pull requests?

**Comment by brian-brazil** [comment]
This is a pretty standard Go project, there's no real special steps.

Can you clean up the go.sum?

**Comment by davidcollom** [comment]
@brian-brazil Cleaned up the `go.sum` as best I could. Looks like CI is happy now.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by davidcollom** [comment]
@brian-brazil Any idea when a new release of blackbox will be release including this PR?

**Pull request merged**
