### PR TITLE
Update CircleCI build

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by simonpasquier** [comment]
As reported [here](https://discuss.circleci.com/t/ipv6-support/13571/5), CircleCI 2.0 doesn't support IPv6 loopback address with the docker executor which breaks the backbox_exporter tests. The [workaround](https://circleci.com/docs/2.0/faq/#can-i-use-ipv6-in-my-tests) is to use the machine executor and configure Docker with IPv6.

**Comment by simonpasquier** [comment]
I agree but unfortunately I can replicate the same failure as reported by [CircleCI](https://circleci.com/gh/prometheus/blackbox_exporter/262) on my machine using Docker and the CircleCI container image. I've enabled logs for the failing test:

```
level=info ts=2018-05-17T14:50:31.033119318Z caller=utils.go:42 msg="Resolving target address" preferred_ip_protocol=ip6                                                                     
level=info ts=2018-05-17T14:50:31.033221039Z caller=utils.go:65 msg="Resolved target address" ip=::1                                                                                         
level=info ts=2018-05-17T14:50:31.033241405Z caller=dns.go:169 msg="Making DNS query" target=[::1]:60900 dial_protocol=udp6 query=example.com type=255                                       
level=error ts=2018-05-17T14:50:31.033272253Z caller=dns.go:174 msg="Error while sending a DNS query" err="dial udp6 [::1]:60900: connect: cannot assign requested address"                 
```

From within the container:
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
39: eth0@if40: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

**Comment by brian-brazil** [comment]
Thanks!

**Comment by simonpasquier** [comment]
@brian-brazil you were too fast :smirk:, https://github.com/prometheus/blackbox_exporter/pull/323 is fixing the releases part...

**Pull request merged**
