### PR TITLE
updated config docs for no_follow_redirects option

### PR DESCRIPTION
**Pull request by wtip**
For example the following would need to be used.

```
prober: http
http:
  valid_status_codes:
  - 200
  - 202
  - 301
  - 302
  no_follow_redirects: true
```

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. These are reference docs, and your suggestion isn't correct in all cases.

**Comment by wtip** [comment]
@brian-brazil When the `no_follow_redirects: true` option is used is there a case where the probe can succeed when the `valid_status_codes` don't include the  `302` code and the server being probed returns a 302 redirect?

Is this reference doc not the correct place to document this example or are you just looking for language that covers all cases?
For example when `no_follow_redirects = false` my comment of `You will also need to use the valid_status_codes option to allow 301 and 302` is incorrect.
Would the following be better?
`If true, you might also need to use the valid_status_codes option to allow 301 and 302`

**Comment by brian-brazil** [comment]
> is there a case where the probe can succeed when the valid_status_codes don't include the 302 code and the server being probed returns a 302 redirect?

The cases are when it doesn't return a 302, such as testing that there isn't a redirect.

> Is this reference doc not the correct place to document this example

What you're proposing are usage guides, not reference docs.

**Comment by wtip** [comment]
Ok so maybe this would be better for the `example.yml` file or would the wiki be better?

**Pull request closed without merging**
