### PR TITLE
Use url.params as parameter for probes

### PR DESCRIPTION
**Pull request by guilhem**
This let probes adding their own configuration

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why do you want to make this change? Probes are configured entirely from the target and the config.

**Comment by guilhem** [comment]
@brian-brazil we plan to add another probes like s3 / cassandra.
This probes need more options than only `target`.

**Comment by guilhem** [comment]
That may be a bad way to do it. We are really open to any suggestion :)
That's why this PR is open

**Comment by SuperQ** [comment]
Cassandra should be monitored with the [jmx_exporter](https://github.com/prometheus/jmx_exporter/blob/master/example_configs/cassandra.yml).

I'm not sure what S3 monitoring you're looking for, but it's probably better done without blackbox probing.

**Comment by guilhem** [comment]
indeed cassandra is monitored with jmx_exporter. But it's clearly not a "blackbox" test.
We are very sensitive to latency and we would like to have an external monitoring of all our services

**Comment by SuperQ** [comment]
What about application-side metrics for Cassandra requests?  You'll catch a lot more latency issues with an application-side histogram of Cassandra requests.

**Comment by guilhem** [comment]
That's perfectly true, but you can't trust every application metrics.
As a service provider, we have to create our own metrics to expose a true SLA.

**Comment by SuperQ** [comment]
Yes, good point.  Expressing different probes in the configuration file is still preferred for the blackbox exporter.  Although it's not really designed for something as complex as Cassandra filesystem operations.

This may be the case where a specialized prober is required.

**Comment by brian-brazil** [comment]
I think that supporting anything beyond very simple and standard protocols would become unmaintainable. While you should be able to some basic S3 monitoring via HTTP, something like C* is too application specific.

As SuperQ says, a separate exporter is the way to go here.

**Comment by guilhem** [comment]
@BarthV is already working on a S3 probe https://github.com/BarthV/blackbox_exporter/tree/s3v2

We don't know if cassandra patches can be upstream here, but this patch will ease maintenance of custom probes (like an "addon").

**Comment by brian-brazil** [comment]
I don't think any probers for specific applications or services will be accepted, you're free to maintain your own versions though.

**Comment by guilhem** [comment]
@brian-brazil I really think it's a good thing :)

This patch just creates a "simpler" interface when an application needs more parameters than only "target".

We may this in the future probes as a lib that can import in our own "blackbox_exporter"

**Comment by brian-brazil** [comment]
> This patch just creates a "simpler" interface when an application needs more parameters than only "target".

It is an explicit design decision of the blackbox exporter not to allow that, the config file has all the config.

**Pull request closed without merging**
