### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by SuperQ**
* Move make test from Travis to CircleCI.
* Drop Travis testing.
* Bump prometheus orb to latest.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
Hmm, the gotestsum test seems to stall. Maybe IPv6 related?

**Comment by brian-brazil** [comment]
It's not immediately obvious from the various retries I've seen/kicked off, it could be related to #713 but I've only seen that failure on v4-only.

**Comment by SuperQ** [comment]
I figured out a couple of the issues.
* We had a TRAVIS specific IPv6 test bypass.
* CircleCI includes `::1 localhost` in the container /etc/hosts file.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
