### PR TITLE
Do not run as root by default in Docker

### PR DESCRIPTION
**Pull request by der-eismann**
Similar in spirit to prometheus/statsd_exporter#202 and others.

### CODE REVIEW

**Comment by SuperQ** [comment]
Looks like this is missing the DCO. You can `git commit -s --amend` to add it.

**Comment by der-eismann** [comment]
Just noticed it, it's added now :slightly_smiling_face:

**Comment by brian-brazil** [comment]
We may actually want root here, for ICMP.

**Comment by der-eismann** [comment]
Can't we workaround this with setuid `chmod u+s` or something like that?

**Comment by brian-brazil** [comment]
That makes no difference, it'd still be running as root.

**Comment by n0guest** [comment]
> We may actually want root here, for ICMP.

Maybe [setcap](https://github.com/docker/labs/tree/master/security/capabilities#step-4-extra-for-experts) would help? I.e:

```
RUN setcap cap_net_raw+ep /path/to/binary
```

**Comment by brian-brazil** [comment]
That's an option.

**Comment by SuperQ** [comment]
`setcap` is a good option. We're still waiting for someone to implement https://github.com/prometheus/blackbox_exporter/issues/147 for root-free operation.

**Pull request closed without merging**
