### PR TITLE
Update prometheus/client_golang to v1.0.0

### PR DESCRIPTION
**Pull request by beorn7**
Signed-off-by: beorn7 <beorn@grafana.com>

### CODE REVIEW

**Comment by beorn7** [comment]
Hmm, I guess update of dependencies has been in limbo for a while now (see a bunch of other PRs and branches). Is that still because of the HTTP keep-alive? @brian-brazil do you have plans to move forward from the status quo?

**Comment by brian-brazil** [comment]
Yes, it's due to keepalive. There is https://github.com/prometheus/common/pull/133, but it's stale.

**Comment by beorn7** [comment]
I'll update this to use common v0.6.0 and will try to fix the other issues.

**Comment by brian-brazil** [comment]
I've literally just finished that.

**Comment by beorn7** [comment]
Even better. Thanks!

**Pull request closed without merging**
