### PR TITLE
Add hostname param support for tls servername

### PR DESCRIPTION
**Pull request by BoringCat**
### Modified for this case
- need to monitor multiple domain which is dynamic resolve to different instance
- instance handle multiple certificate and distinguish with SNI

To monitor more than thousands domain. I can not just create config for prometheus and blackbox-exporter dynamiced. If each domain need it own `job` and `module`. The config file will to large and may be affect prometheus performance.

So it will be perfect if single `module` can handle all request just with hostname param like http probe 👍

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks. This would require tests.

**Comment by electron0zero** [comment]
fyi: https://github.com/prometheus/blackbox_exporter/pull/981 is also fixing the same issue.

**Comment by BoringCat** [comment]
> fyi: #981 is also fixing the same issue.

Well, after i make this PR. My target was changed. I need to known more infomation about the certificate. I'm now creating my own exporter. So I have no time work for this. If #981 can fix it and pass test. Please close this.

**Comment by electron0zero** [comment]
> > fyi: #981 is also fixing the same issue.
> 
> Well, after i make this PR. My target was changed. I need to known more infomation about the certificate. I'm now creating my own exporter. So I have no time work for this. If #981 can fix it and pass test. Please close this.

closing in favor of #981

**Pull request closed without merging**
