### PR TITLE
Adding support for basic auth

### PR DESCRIPTION
**Pull request by mbrewster**
Implemented support for basic auth for the http probe.

### CODE REVIEW

**Comment by brian-brazil** [comment]
We should probably factor out the auth support in Prometheus rather than slowly reimplementing it in other components.

**Comment by mbrewster** [comment]
Would you envision the username/pwd being passed through via the scrape config?

**Comment by brian-brazil** [comment]
Yes, the same way it's done in Prometheus. There's some security issues here touched on in #5

**Comment by mbrewster** [comment]
So it would be a new config element unique to the blackbox_exporter that passed a username/pwd in a manner similar to how credentials are passed for the sd configs? I don't see how we get around actually implementing the auth header in the request on the blackbox side.

**Comment by brian-brazil** [comment]
We can have https://github.com/prometheus/prometheus/blob/master/retrieval/target.go#L257 as a part of a shared library between the two systems.

**Pull request closed without merging**
