### PR TITLE
Add a Basic Auth example to the README.

### PR DESCRIPTION
**Pull request by SuperQ**

### CODE REVIEW

**Comment by SuperQ** [comment]
But [here ](https://github.com/prometheus/blackbox_exporter/issues/53#issuecomment-234250146) you said to use headers

**Comment by SuperQ** [comment]
Otherwise, we should simply implement it like https://github.com/prometheus/blackbox_exporter/pull/23

**Comment by brian-brazil** [comment]
Ah, I was looking for #23 and couldn't find it.

**Comment by SuperQ** [comment]
A variation on #23 would work just fine for me.  Let me know what you're thinking, this doesn't seem like a complicated code change.

**Comment by brian-brazil** [comment]
It's more factoring out the relevant bit of code into common, and then reusing it here. We'll be wanting the same in the AM too.

**Comment by SuperQ** [comment]
For now, can we document a workaround?

**Comment by brian-brazil** [comment]
Considering how we currently treat secrets in configs, I don't think we should be encouraging users to do things that'd bypass those protections (not that the blackbox exporter exposes its config yet).

**Comment by SuperQ** [comment]
Secrets in configs seems fine to me, it's basically the same as community strings in the snmp exporter.

**Comment by brian-brazil** [comment]
Secrets in places where you don't expect them to be is a problem though. Random headers are not where you expect secrets.

**Comment by SuperQ** [comment]
I wouldn't call `Authorization` obscure or random.

**Comment by discordianfish** [comment]
I think it's perfectly fine to store secrets in a config (are we really discussing this?). I really don't get what the problem is. People want to use basic auth, we support basic auth (by setting headers) so we should tell people how to do it..?
Maybe add a sentence like "Basic auth is not officially supported but this is how you can do it anyway"?

**Comment by brian-brazil** [comment]
> I think it's perfectly fine to store secrets in a config (are we really discussing this?).

It's fine if it's in a place we expect to have secrets. HTTP headers are not such a place.

**Comment by SuperQ** [comment]
There's nothing surprising about using headers for basic auth.

It says it in in the docs for the [golang helper](https://golang.org/pkg/net/http/#Request.SetBasicAuth).  Which is just a wrapper for [request.Set.Header()](https://golang.org/src/net/http/request.go?s=28267:28324#L860).

**Comment by discordianfish** [comment]
@brian-brazil The 'Authorization' header is there since forever and it was always meant to include credentials. Is there any form of proof or argument that would change your mind?

**Comment by brian-brazil** [comment]
There's a difference between implementation details and user-facing APIs. In Prometheus we obtain this information via the `basic_auth` fields, and the blackbox exporter should follow that.

**Comment by brian-brazil** [comment]
Basic auth (and the other auth options) are now supported in the usual Prometheus, though not released yet. There's also an example in the readme (at least for a little bit, that's about to get rejigged).

**Comment by SuperQ** [comment]
Nice! Thanks!

**Pull request closed without merging**
