### PR TITLE
Delay init of http phase values

### PR DESCRIPTION
**Pull request by SuperQ**
Don't init http probe phase labels until we're ready to send the
request.

Avoids exposing 0 value samples for things we haven't started to
measure.

Fix http resolve timing to report lookup time even if it's an error
(ie not found).

Fixes: https://github.com/prometheus/blackbox_exporter/issues/579

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Review by dgl — APPROVED** [review]

**Review by electron0zero — APPROVED** [review]

**Comment by roidelapluie** [comment]
Mmmmh that's an interesting PR, it means that averages etc will only work when a phase is executed, I am not sure we should do this.

**Comment by SuperQ** [comment]
@roidelapluie It's a difficult choice. The problem is we emit 0 for things we have explicitly not measured, which is what the original issue is about.

**Comment by roidelapluie** [comment]
`Why this is a problem: if you perform any analytics over those metrics (eg percentiles, or min) it would be skewed.`

But if probe_success == 0 you should not run analytics over them either.

**Comment by zerkms** [comment]
@roidelapluie 

> But if probe_success == 0 you should not run analytics over them either.

how would you exclude those series that were obtained with an error

**Comment by roidelapluie** [comment]
I've been thinking this further.

When HAProxy Exporter can not scrape HAProxy, it does not return zero-ed metrics. We should do the same here.

**Review by roidelapluie — APPROVED** [review]

**Comment by SuperQ** [comment]
I also added a fix for the "resolve" phase. It now accounts for the resolve phase time even if the resolve result is a failure.

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
