### PR TITLE
Update maintainer.

### PR DESCRIPTION
**Pull request by SuperQ**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Uhm, I'm actively maintaining this repository and not currently looking for a replacement. Did you send this by accident?

**Comment by SuperQ** [comment]
No, this is not by accident.  I am proposing removing you as official maintainer if you're unwilling to maintain the documentation.

**Comment by brian-brazil** [comment]
The documentation is maintained, I'm not aware of any inaccuracies in the current readme (just fixed one small mistake).

**Comment by juliusv** [comment]
@SuperQ @brian-brazil People, I'm tied up on a business trip at the moment, but from what I've read here and on the sidelines from various people, it seems to me that there is some conflict resolution required (and also some general thinking from all of us about how we handle certain community matters). I'd be happy to moderate that and talk to everyone individually once I get back (last week of June), but at the moment, I can't get involved much.

Would that be accepted and useful?

**Comment by SuperQ** [comment]
Fine with me.

**Comment by beorn7** [comment]
On a general note, not related to any particular conflict, I think it makes sense to involve more people as repository maintainers, and balance the number of maintained repository more evenly among them.

**Comment by fabxc** [comment]
This was not discussed with anyone beforehand and I consider this highly unprofessional and aggressive. Frankly, it violates our [code of conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md).

Please bring up concerns with the right people on the right channels in the future.

**Comment by discordianfish** [comment]
@fabxc Just to avoid such things in the future, can you elaborate how this violates our code of conduct?

I understand if you prefer to keep this conflict behind closed doors and I find this approach aggressive too, yet just stating it's a violation of our CoC and deleting the branch without elaboration is quite aggressive too. Let's better leave moderating this to @juliusv though.

**Comment by juliusv** [comment]
I had private talks with the involved parties here, also about broader issues.

I agree that just opening a PR like this is not the way to go about it, CoC violation or not.

I generally support distributing repositories over a larger base of maintainers, but in contentious cases like this one I would like to see the reasoning discussed between all involved parties first, and have a core developer vote if necessary. For this kind question discussion here, prometheus-team@ is probably the best forum, though I'm not 100% sure about that either and I'll treat that as a working opinion that may change in the future.

**Comment by fabxc** [comment]
"Other unethical or unprofessional conduct."

Taking someone of the maintainers file is an action that happens after a decision. Doing it without that decision being made is not appropriate and disrespectful.

This is about making the decision in the first place – not necessarily behind closed doors.
As stated in my last sentence, this is not closing the discussion but the action of taking Brian off of the list of maintainers without this being agreed upon anywhere.
Feel free to open a proper thread on this on the mailing list.

With that said, a repository maintainer is not the person to make authoritative decision for the repository in face of strong disagreement. I assume that this was the consequence of such technical disagreement elsewhere. So promoting someone (without agreement) to a maintainer is no route to push a technical position through.

**Comment by beorn7** [comment]
> Taking someone of the maintainers file is an action that happens after a decision. Doing it without that decision being made is not appropriate and disrespectful.

To be fair, it should be noted that this is just a PR (R for "request") and not a change done. The only rude part here is _No description provided._ This should have been _I request to make @discordianfish the maintainer of this repository for the following reasons: … Please discuss._

As comparison, a change to the roadmap of the project as a whole was _merged_ against the explicitly stated objection of a core developer, without a vote happening. Even after multiple requests to revert the change, it didn't happen. In fact, it hasn't happened until today.

**Comment by fabxc** [comment]
> This should have been I request to make @discordianfish the maintainer of this repository for the following reasons: … Please discuss.

Removal of the original one is the main issue.

No one denies the need for a discussion on this. But please let's have it in an open way on the mailing list.
Same goes for the roadmap issue you mentioned. It was equally wrong, though less personal, and should be reevaluated. We didn't do a good job following up on this.

Yet, two wrongs don't make one right.

To move these discussions to appropriate places I opened two threads ([blackbox_exporter maintainer](https://groups.google.com/forum/#!topic/prometheus-developers/OtdbY0warzk), [roadmap](https://groups.google.com/forum/#!topic/prometheus-developers/A-BCPGUSYzw)) on prometheus-developers. Let's please take it there.

**Pull request closed without merging**
