### PR TITLE
Docker image generation not requiring building the project outside docker

### PR DESCRIPTION
**Pull request by dcaba**
Introducing multistage build in the main dockerfile so we don't depend on an external build to generate a dockered version of the software

### CODE REVIEW

**Comment by brian-brazil** [comment]
This file is part of our build system, if you want to change how it all works the promu repo is where to propose that.

**Comment by dcaba** [comment]
Thanks for the info... I see your build system is created with the assumption the binary its build outside docker, and then packaged in all formats you support, including docker, to ensure the binary is the same, so that's why you are not doing a separate build for docker directly in your dockerfile, that could to external users, as it would be easier to build and get an image ready, just with a single command... just to facilitate that use case: what do you think if we just add to the readme that we can run this software by pulling your already build docker image? 

[https://hub.docker.com/r/prom/blackbox-exporter/tags](https://hub.docker.com/r/prom/blackbox-exporter/tags)

Happy to submit a proposal

**Comment by brian-brazil** [comment]
The readme is a bit outdated, using a released build should be first.

**Comment by dcaba** [comment]
Proposal [here](https://github.com/prometheus/blackbox_exporter/pull/452) only covering README updates. Closing this PR. Thanks!

**Pull request closed without merging**
